# Generated by Django 5.2.4 on 2025-08-05 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('executive', 'Dashboard Executivo'), ('projects', 'Dashboard de Projetos'), ('donations', 'Dashboard de Doações'), ('users', 'Dashboard de Usuários'), ('financial', 'Dashboard Financeiro'), ('impact', 'Dashboard de Impacto')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, help_text='Configuração dos widgets e layout')),
                ('cached_data', models.JSONField(default=dict, help_text='Dados em cache para performance')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Analytics',
                'verbose_name_plural': 'Dashboards Analytics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('count', 'Contador'), ('sum', 'Soma'), ('average', 'Média'), ('percentage', 'Percentual'), ('ratio', 'Razão'), ('currency', 'Moeda'), ('custom', 'Personalizada')], max_length=20)),
                ('aggregation', models.CharField(choices=[('sum', 'Soma'), ('avg', 'Média'), ('count', 'Contagem'), ('max', 'Máximo'), ('min', 'Mínimo')], default='sum', max_length=20)),
                ('query_config', models.JSONField(default=dict, help_text='Configuração da consulta SQL/ORM')),
                ('unit', models.CharField(blank=True, help_text='Unidade de medida (€, %, pessoas, etc.)', max_length=20)),
                ('decimal_places', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Definição de Métrica',
                'verbose_name_plural': 'Definições de Métricas',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('impact', 'Relatório de Impacto'), ('financial', 'Relatório Financeiro'), ('progress', 'Relatório de Progresso'), ('executive', 'Dashboard Executivo'), ('quarterly', 'Relatório Trimestral'), ('annual', 'Relatório Anual'), ('custom', 'Relatório Personalizado')], max_length=20)),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Completo'), ('failed', 'Falhou'), ('scheduled', 'Agendado')], default='generating', max_length=20)),
                ('filters', models.JSONField(default=dict, help_text='Filtros aplicados na geração do relatório')),
                ('data', models.JSONField(default=dict, help_text='Dados processados do relatório')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral')], max_length=20, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('impact', 'Relatório de Impacto'), ('financial', 'Relatório Financeiro'), ('progress', 'Relatório de Progresso'), ('executive', 'Dashboard Executivo'), ('quarterly', 'Relatório Trimestral'), ('annual', 'Relatório Anual'), ('custom', 'Relatório Personalizado')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('annually', 'Anual')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Configuração e filtros do relatório')),
                ('email_recipients', models.TextField(blank=True, help_text='Emails adicionais separados por vírgula')),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Agendado',
                'verbose_name_plural': 'Relatórios Agendados',
                'ordering': ['name'],
            },
        ),
    ]
