# Generated by Django 5.2.4 on 2025-08-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_donation_status_change', models.BooleanField(default=True, verbose_name='Mudanças de Status')),
                ('notify_donation_comments', models.BooleanField(default=True, verbose_name='Novos Comentários')),
                ('notify_payment_verification', models.BooleanField(default=True, verbose_name='Verificação de Pagamento')),
                ('notify_new_donations', models.BooleanField(default=True, verbose_name='Novas Doações')),
                ('notify_donor_comments', models.BooleanField(default=True, verbose_name='Comentários de Doadores')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='Notificações no App')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('donation_created', 'Doação Criada'), ('donation_status_changed', 'Status da Doação Alterado'), ('donation_comment_added', 'Novo Comentário na Doação'), ('donation_approved', 'Doação Aprovada'), ('donation_rejected', 'Doação Rejeitada'), ('payment_verified', 'Pagamento Verificado'), ('admin_comment', 'Comentário do Administrador'), ('donor_comment', 'Comentário do Doador')], max_length=30, verbose_name='Tipo de Notificação')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('related_donation_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Doação')),
                ('related_comment_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Comentário')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviada')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de Ação')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Texto da Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
