# Generated by Django 5.2.4 on 2025-08-10 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Técnica'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('construction', 'Construção'), ('administrative', 'Administrativa'), ('social', 'Social'), ('other', 'Outra')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilidade de Voluntário',
                'verbose_name_plural': 'Habilidades de Voluntários',
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('estimated_hours', models.PositiveIntegerField(help_text='Horas estimadas para completar')),
                ('people_helped_estimate', models.PositiveIntegerField(default=1, help_text='Número estimado de pessoas que serão ajudadas')),
                ('urgency_level', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, to='volunteers.volunteerskill')),
            ],
            options={
                'verbose_name': 'Oportunidade de Voluntariado',
                'verbose_name_plural': 'Oportunidades de Voluntariado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Descrição sobre o voluntário')),
                ('availability', models.CharField(choices=[('weekdays', 'Dias da semana'), ('weekends', 'Fins de semana'), ('evenings', 'Noites'), ('flexible', 'Flexível')], default='flexible', max_length=50)),
                ('max_hours_per_week', models.PositiveIntegerField(default=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, to='volunteers.volunteerskill')),
            ],
            options={
                'verbose_name': 'Perfil de Voluntário',
                'verbose_name_plural': 'Perfis de Voluntários',
            },
        ),
        migrations.CreateModel(
            name='VolunteerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='award', max_length=50)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='volunteers.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Conquista de Voluntário',
                'verbose_name_plural': 'Conquistas de Voluntários',
                'ordering': ['-earned_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Candidatou-se'), ('accepted', 'Aceito'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('rejected', 'Rejeitado')], default='applied', max_length=20)),
                ('application_message', models.TextField(blank=True, help_text='Mensagem do voluntário ao se candidatar')),
                ('actual_hours', models.PositiveIntegerField(blank=True, help_text='Horas reais trabalhadas', null=True)),
                ('people_helped', models.PositiveIntegerField(blank=True, help_text='Pessoas realmente ajudadas', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas do administrador')),
                ('admin_rating', models.PositiveIntegerField(blank=True, help_text='Avaliação do administrador (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('volunteer_feedback', models.TextField(blank=True, help_text='Feedback do voluntário')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='volunteers.volunteeropportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='volunteers.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Participação em Voluntariado',
                'verbose_name_plural': 'Participações em Voluntariado',
                'ordering': ['-created_at'],
                'unique_together': {('volunteer', 'opportunity')},
            },
        ),
    ]
