# Generated by Django 5.2.4 on 2025-08-10 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Género')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Alternativo')),
                ('province', models.CharField(default='Cabo Delgado', max_length=100, verbose_name='Província')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('administrative_post', models.CharField(max_length=100, verbose_name='Posto Administrativo')),
                ('locality', models.CharField(max_length=100, verbose_name='Localidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_details', models.TextField(blank=True, verbose_name='Detalhes do Endereço')),
                ('education_level', models.CharField(choices=[('nenhuma', 'Nenhuma escolaridade'), ('primario', 'Ensino Primário'), ('secundario', 'Ensino Secundário'), ('tecnico', 'Ensino Técnico'), ('superior', 'Ensino Superior')], max_length=20, verbose_name='Nível de Escolaridade')),
                ('employment_status', models.CharField(choices=[('desempregado', 'Desempregado'), ('informal', 'Trabalho Informal'), ('formal', 'Trabalho Formal'), ('autonomo', 'Autônomo'), ('estudante', 'Estudante'), ('aposentado', 'Aposentado'), ('domestico', 'Trabalho Doméstico')], max_length=20, verbose_name='Situação de Emprego')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Mensal (MZN)')),
                ('family_status', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao', 'União de Facto'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, verbose_name='Estado Civil')),
                ('family_members_count', models.IntegerField(default=1, verbose_name='Número de Membros da Família')),
                ('children_count', models.IntegerField(default=0, verbose_name='Número de Filhos')),
                ('elderly_count', models.IntegerField(default=0, verbose_name='Número de Idosos')),
                ('disabled_count', models.IntegerField(default=0, verbose_name='Número de Pessoas com Deficiência')),
                ('is_displaced', models.BooleanField(default=False, verbose_name='Pessoa Deslocada')),
                ('displacement_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo do Deslocamento')),
                ('has_chronic_illness', models.BooleanField(default=False, verbose_name='Doença Crónica na Família')),
                ('chronic_illness_details', models.TextField(blank=True, verbose_name='Detalhes da Doença Crónica')),
                ('priority_needs', models.TextField(verbose_name='Necessidades Prioritárias')),
                ('additional_information', models.TextField(blank=True, verbose_name='Informações Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Perfil Verificado')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Verificação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_beneficiary_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Beneficiário',
                'verbose_name_plural': 'Perfis de Beneficiários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identidade', 'Documento de Identidade'), ('residencia', 'Comprovativo de Residência'), ('renda', 'Comprovativo de Renda'), ('medico', 'Relatório Médico'), ('familia', 'Composição Familiar'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to='beneficiary_documents/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_beneficiary_documents', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaries.beneficiaryprofile')),
            ],
            options={
                'verbose_name': 'Documento do Beneficiário',
                'verbose_name_plural': 'Documentos dos Beneficiários',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('alimentar', 'Apoio Alimentar'), ('medico', 'Apoio Médico'), ('educacao', 'Apoio Educacional'), ('habitacao', 'Apoio Habitacional'), ('emprego', 'Apoio ao Emprego'), ('psicologico', 'Apoio Psicológico'), ('juridico', 'Apoio Jurídico'), ('emergencia', 'Apoio de Emergência'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Apoio')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Solicitação')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('urgency', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('estimated_beneficiaries', models.IntegerField(default=1, verbose_name='Número de Beneficiários')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado (MZN)')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('needed_by_date', models.DateField(blank=True, null=True, verbose_name='Necessário Até')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revisão')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Real (MZN)')),
                ('actual_beneficiaries', models.IntegerField(blank=True, null=True, verbose_name='Beneficiários Reais')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='beneficiaries.beneficiaryprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Apoio',
                'verbose_name_plural': 'Solicitações de Apoio',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('pergunta', 'Pergunta'), ('atualizacao', 'Atualização'), ('documento', 'Documento'), ('feedback', 'Feedback'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Mensagem')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('attachment', models.FileField(blank=True, upload_to='beneficiary_communications/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='beneficiaries.supportrequest')),
            ],
            options={
                'verbose_name': 'Comunicação com Beneficiário',
                'verbose_name_plural': 'Comunicações com Beneficiários',
                'ordering': ['-created_at'],
            },
        ),
    ]
