# Generated by Django 5.2.4 on 2025-08-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
