# Generated by Django 5.2.4 on 2025-08-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Método')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('account_details', models.JSONField(default=dict, verbose_name='Detalhes da Conta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Método de Doação',
                'verbose_name_plural': 'Métodos de Doação',
            },
        ),
        migrations.CreateModel(
            name='DonationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_donors', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatística de Doação',
                'verbose_name_plural': 'Estatísticas de Doações',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('currency', models.CharField(default='MZN', max_length=3, verbose_name='Moeda')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferência Bancária'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('cash', 'Dinheiro'), ('other', 'Outro')], max_length=20, verbose_name='Método de Pagamento')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referência do Pagamento')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='donations/proofs/', verbose_name='Comprovante')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('submitted', 'Enviada'), ('under_review', 'Em Análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Análise')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
                ('donor_message', models.TextField(blank=True, verbose_name='Mensagem do Doador')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Finalidade')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Doação Anônima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donations', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Nota Interna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='donations.donation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
