# Generated by Django 5.2.4 on 2025-08-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.donationmethod', verbose_name='Método de Doação'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferência Bancária'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('cash', 'Dinheiro'), ('other', 'Outro')], max_length=20, null=True, verbose_name='Método de Pagamento (Legacy)'),
        ),
    ]
