# Generated by Django 5.2.4 on 2025-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_donation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='donations/proofs/', verbose_name='Comprovante'),
        ),
    ]
