# Generated by Django 4.2.7 on 2025-08-02 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=500, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagem em destaque')),
                ('featured_image_caption', models.CharField(blank=True, max_length=300, verbose_name='Legenda da imagem principal')),
                ('featured_image_credit', models.CharField(blank=True, max_length=200, verbose_name='Crédito da imagem principal')),
                ('featured_image_source_url', models.URLField(blank=True, verbose_name='URL da fonte da imagem principal')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descrição')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Palavras-chave')),
                ('meta_title', models.CharField(blank=True, help_text='Título otimizado para SEO (máx. 70 caracteres)', max_length=70, verbose_name='Título SEO')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canônica para evitar conteúdo duplicado', verbose_name='URL Canônica')),
                ('og_title', models.CharField(blank=True, help_text='Título para redes sociais (máx. 95 caracteres)', max_length=95, verbose_name='Título Open Graph')),
                ('og_description', models.CharField(blank=True, help_text='Descrição para redes sociais (máx. 200 caracteres)', max_length=200, verbose_name='Descrição Open Graph')),
                ('og_image', models.ImageField(blank=True, help_text='Imagem para redes sociais (recomendado: 1200x630px)', null=True, upload_to='blog_images/og/', verbose_name='Imagem Open Graph')),
                ('twitter_title', models.CharField(blank=True, max_length=70, verbose_name='Título Twitter')),
                ('twitter_description', models.CharField(blank=True, max_length=200, verbose_name='Descrição Twitter')),
                ('schema_type', models.CharField(choices=[('Article', 'Artigo'), ('NewsArticle', 'Artigo de Notícia'), ('BlogPosting', 'Post de Blog'), ('Review', 'Resenha'), ('HowTo', 'Tutorial')], default='Article', max_length=50, verbose_name='Tipo de Schema')),
                ('focus_keyword', models.CharField(blank=True, help_text='Palavra-chave principal para este post', max_length=100, verbose_name='Palavra-chave principal')),
                ('seo_score', models.FloatField(default=0.0, help_text='Pontuação automática de SEO (0-100)', verbose_name='Pontuação SEO')),
                ('readability_score', models.FloatField(default=0.0, help_text='Pontuação de legibilidade do conteúdo', verbose_name='Pontuação de Legibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='Tempo de leitura (minutos)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
            ],
            options={
                'verbose_name': 'Assinante da Newsletter',
                'verbose_name_plural': 'Assinantes da Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL da imagem')),
                ('image_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Legenda')),
                ('credit', models.CharField(blank=True, max_length=200, verbose_name='Crédito/Fonte')),
                ('source_url', models.URLField(blank=True, verbose_name='URL da fonte')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='Fotógrafo')),
                ('license_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de licença')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_credits', to='blog.blogpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Crédito de Imagem',
                'verbose_name_plural': 'Créditos de Imagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nome do autor')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email do autor')),
                ('content', models.TextField(verbose_name='Comentário')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='blog_blogpo_categor_c7bd72_idx'),
        ),
    ]
