# Generated by Django 4.2.7 on 2025-08-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Legenda da imagem principal'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Crédito da imagem principal'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_source_url',
            field=models.URLField(blank=True, verbose_name='URL da fonte da imagem principal'),
        ),
        migrations.CreateModel(
            name='ImageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL da imagem')),
                ('image_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Legenda')),
                ('credit', models.CharField(blank=True, max_length=200, verbose_name='Crédito/Fonte')),
                ('source_url', models.URLField(blank=True, verbose_name='URL da fonte')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='Fotógrafo')),
                ('license_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de licença')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_credits', to='blog.blogpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Crédito de Imagem',
                'verbose_name_plural': 'Créditos de Imagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
