# Generated by Django 4.2.7 on 2025-08-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Hashtags separadas por vírgula (ex: #educacao, #cabo-delgado, #solidariedade)', verbose_name='Hashtags'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Impede que motores de busca sigam links neste post', verbose_name='Não seguir links (nofollow)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Impede que motores de busca indexem este post', verbose_name='Não indexar (noindex)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_type',
            field=models.CharField(choices=[('article', 'Artigo'), ('website', 'Website'), ('blog', 'Blog'), ('news', 'Notícia')], default='article', max_length=50, verbose_name='Tipo Open Graph'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='robots_txt',
            field=models.CharField(blank=True, help_text='Diretivas personalizadas para robots.txt', max_length=200, verbose_name='Diretivas Robots'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_card',
            field=models.CharField(choices=[('summary', 'Resumo'), ('summary_large_image', 'Resumo com imagem grande'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', max_length=50, verbose_name='Tipo Twitter Card'),
        ),
    ]
