# Generated by Django 5.2.4 on 2025-08-10 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_district_province_to_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sender_type', models.CharField(choices=[('admin', 'Administrator'), ('partner', 'Partner')], max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='partnership_attachments/')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partner_messages', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_messages', to='core.project')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Message',
                'verbose_name_plural': 'Partner Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('implementer', 'Project Implementer'), ('supporter', 'Project Supporter'), ('advisor', 'Project Advisor'), ('sponsor', 'Project Sponsor')], default='implementer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes about the partnership assignment')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Specific terms for this partnership')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text="Partner's response to the assignment")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_partnerships', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_assignments', to='core.project')),
            ],
            options={
                'verbose_name': 'Partner Project Assignment',
                'verbose_name_plural': 'Partner Project Assignments',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'project')},
            },
        ),
    ]
