# Generated by Django 5.2.4 on 2025-08-05 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_project_options_remove_project_beneficiaries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('before', 'Antes'), ('progress', 'Progresso'), ('after', 'Depois'), ('team', 'Equipe'), ('community', 'Comunidade'), ('infrastructure', 'Infraestrutura'), ('events', 'Eventos')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_gallery_images', to='core.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['order', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_impacted', models.PositiveIntegerField(default=0)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('completed_milestones', models.PositiveIntegerField(default=0)),
                ('total_milestones', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.project')),
            ],
            options={
                'verbose_name': 'Métrica do Projeto',
                'verbose_name_plural': 'Métricas dos Projetos',
            },
        ),
        migrations.CreateModel(
            name='ProjectMetricsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('people_impacted', models.PositiveIntegerField(default=0)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('planning', 'Planejamento'), ('execution', 'Execução'), ('monitoring', 'Monitoramento'), ('completion', 'Finalização')], max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_metrics_entries', to='core.project')),
            ],
            options={
                'verbose_name': 'Registro de Métrica',
                'verbose_name_plural': 'Registros de Métricas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in-progress', 'Em Progresso'), ('completed', 'Concluído'), ('delayed', 'Atrasado')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, to='project_tracking.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_milestones', to='core.project')),
            ],
            options={
                'verbose_name': 'Marco do Projeto',
                'verbose_name_plural': 'Marcos dos Projetos',
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('milestone', 'Marco/Objetivo'), ('progress', 'Progresso'), ('issue', 'Problema'), ('achievement', 'Conquista')], default='progress', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('people_impacted', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('progress_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tracking_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='core.project')),
            ],
            options={
                'verbose_name': 'Atualização do Projeto',
                'verbose_name_plural': 'Atualizações dos Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Vídeo'), ('document', 'Documento'), ('report', 'Relatório')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='project_evidence/%Y/%m/')),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_evidence', to='core.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='project_tracking.projectupdate')),
            ],
            options={
                'verbose_name': 'Evidência do Projeto',
                'verbose_name_plural': 'Evidências dos Projetos',
                'ordering': ['-upload_date'],
            },
        ),
    ]
