# Generated by Django 5.2.4 on 2025-08-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevidence',
            name='type',
            field=models.CharField(choices=[('image', 'Imagem'), ('photo', 'Foto'), ('video', 'Vídeo'), ('document', 'Documento'), ('report', 'Relatório'), ('certificate', 'Certificado'), ('other', 'Outro')], max_length=20),
        ),
    ]
