# Generated by Django 4.2.7 on 2025-07-29 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('subject', models.CharField(choices=[('general', 'Informações Gerais'), ('volunteer', 'Voluntariado'), ('donation', 'Doações'), ('partnership', 'Parcerias'), ('media', 'Imprensa'), ('other', 'Outros')], default='general', max_length=20, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Respondida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descrição curta')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Cor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficiaries_count', models.PositiveIntegerField(default=0, verbose_name='Número de beneficiários')),
                ('communities_reached', models.PositiveIntegerField(default=0, verbose_name='Comunidades alcançadas')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MOZ SOLIDÁRIA', max_length=100, verbose_name='Nome do Site')),
                ('site_description', models.TextField(blank=True, verbose_name='Descrição do Site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Função')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('content', models.TextField(verbose_name='Depoimento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descrição curta')),
                ('location', models.CharField(max_length=100, verbose_name='Localização')),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('active', 'Ativo'), ('completed', 'Concluído'), ('suspended', 'Suspenso')], default='planning', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagem principal')),
                ('beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Beneficiários')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Orçamento')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
