# Generated by Django 5.2.4 on 2025-08-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cause_certification_skill_userprofile_volunteer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='beneficiaries',
        ),
        migrations.AddField(
            model_name='project',
            name='accepts_donations',
            field=models.BooleanField(default=True, verbose_name='Aceita doações'),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo detalhado em HTML', verbose_name='Conteúdo completo'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_beneficiaries',
            field=models.PositiveIntegerField(default=0, help_text='Número atual de beneficiários sendo atendidos', verbose_name='Beneficiários atuais'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Palavras-chave SEO'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Título SEO'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Progresso do projeto em porcentagem (0-100)', verbose_name='Progresso (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor arrecadado'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_beneficiaries',
            field=models.PositiveIntegerField(default=0, help_text='Número total de beneficiários que se pretende atender', verbose_name='Meta de beneficiários'),
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', max_length=20, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone Lucide React (ex: Building, Heart, etc.)', max_length=50, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Categoria de Projeto',
                'verbose_name_plural': 'Categorias de Projetos',
                'ordering': ['program__name', 'order', 'name'],
                'unique_together': {('program', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='project_gallery/', verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Imagem destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Projetos',
                'ordering': ['project', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_updates/', verbose_name='Imagem')),
                ('is_milestone', models.BooleanField(default=False, help_text='Marcar se esta atualização é um marco importante', verbose_name='É um marco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Atualização de Projeto',
                'verbose_name_plural': 'Atualizações de Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
