# Generated by Django 5.2.4 on 2025-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options_remove_project_beneficiaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Província'),
        ),
    ]
